name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set My Api Key
      if: success()
      uses: my-org/my-action@v1
      with:
        api_key: ${{ secrets.YT_API_KEY }}
