name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.YT_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: print my Api key
      run: echo ${{ secrets.YT_API_KEY }}
