name: YD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:  
  display:
    runs-on: ubuntu-latest
    env:
      platform: Azure
      region: central
      profile_path: profile/
      MY_SECRET: ${{ secrets.API_KEY }}

  steps:
    - name: Display custom environment variables
    run: |
      echo "The platform is: ${{ env.platform }}"
      echo "The platform is: $region"
      echo "My secret: ${{ secrets.API_KEY }}"


