name: "Youtube Downloader"
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Environment
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "My secret: ${{ secrets.API_KEY }}"

